spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      multi-tenancy: SCHEMA
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        multiTenancy: SCHEMA
    show-sql: true
    open-in-view: false

  flyway:
    enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.hbm2ddl: DEBUG